version: '3.8'

services:
  app:
    image: node:20-alpine
    container_name: tourpointer-ui-builder
    working_dir: /app
    volumes:
      - ./:/app
      - ${PWD}/build:/app/dist
    command: >
      sh -c "npm install && npm run build"