version: '3.8'

services:
  app:
    image: node:20-alpine
    container_name: route-suggestor-ui-builder
    working_dir: /app
    environment:
      - HOST_UID=${UID}
      - HOST_GID=${GID}
    volumes:
      - ./:/app
    user: "${HOST_UID}:${HOST_GID}"
    command: >
      sh -c "npm install && npm run build"