version: '3.8'

services:
  app:
    image: node:20-alpine
    container_name: route-suggestor-ui-builder
    working_dir: /app
    volumes:
      - ./:/app
    user: "${HOST_UID}:${HOST_GID}"
    command: >
      sh -c "npm install && npm run build"