name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Clean workspace directory
        run: rm -rf "${{ github.workspace }}/*"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: ./source

      - name: Build app
        run: docker-compose up --build

      - name: Copy build files to caddy serve path
        run: |
          rm -rf /srv/caddy/tourpointer/*
          cp -r ./build/* /srv/caddy/tourpointer/