name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Print user information
        run: |
          echo "User running this step:"
          whoami
          echo "Current user ID and group ID:"
          id
          echo "List of current user's home directory files:"
          ls -la ~

      - name: Clean workspace directory
        run: sudo rm -rf "${{ github.workspace }}/*"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env.production file
        run: |
          echo "VITE_API_BASE_URL=http://route-suggestor-api.tomaskri.com" > .env.production

      - name: Remove existing container if it exists
        run: docker rm -f route-suggestor-ui-builder || true

      - name: Build app
        run: docker-compose up --build

      - name: Copy build files to caddy serve path
        run: |
          sudo mkdir -p /srv/caddy/route-suggestor
          sudo rm -rf /srv/caddy/route-suggestor/*
          sudo cp -r ./dist/* /srv/caddy/route-suggestor/